language: cpp

sudo: required

compiler:
- g++

env:
- PURPOSE=compile
- PURPOSE=unittest

before_install:

install:
- sudo apt-get install libgflags-dev
- sudo apt-get install libglog-dev
- sudo apt-get install librocksdb-dev

before_script:

script:
- sh build_in_travis_ci.sh

after_failure:
